% Sinr
sinr(txs,pm, ...
    'ReceiverGain',rxGain, ...
    'ReceiverAntennaHeight',rxAntennaHeight, ...
    'ReceiverNoisePower',rxNoisePower, ...
    'MaxRange',isd, ...
    'Resolution',isd/20)
